# Name of your site (this will show up at the top of your page and in the RSS feed)
name: 'Intimate Fields'

# Short description (goes below the title; it will also be used in the RSS feed)
description: ''

# Your name, as you want it to appear underneath each post and in the footer
author: ''

# social media
github: 'https://hyperrhiz.github.io/intimate-fields'
twitter: 'https://twitter.com/intimatefields'

# Your email if you want it to be linked on the contact page
author_email: 'polyrhetor@gmail.com'

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 
baseurl:

# sitemap
gems:
  - jekyll-sitemap
  
# force inclusion of dot files for folder password protection
include: ['.htaccess', '.htpasswd']

                          
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://hyperrhiz.github.io/intimate-fields

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: none

encoding: utf-8

# How many articles do you wish to appear on the front page:
#paginate: 20

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]